Gemfile
Addition "haml-rails" to Gemfile
To use haml&scss.
=> haml-rails import

README.md, db/schema.rb
メルカリのDB設計/READMEに記載
❶誤記修正
news/new  string
announces/announce string
images/image string
users/birthday integer
cards/name string
❷addressesテーブルとcellphoneテーブルをusersテーブルから切り離し
❸usersテーブルにおいて
nameカラムをlast_nameとfirst_nameに分離
birthdayカラムをbirthday_year, birthday_month, birthday_dateに分離
❹evaluationsテーブルのあたりを迷走してます・・・
[20200123 データベース ER 図　メルカリ.pdf](https://github.com/fukumototakaaki/mercari/files/4098568/20200123.ER.pdf)
開発前にある程度DB設計を済ませ、開発しながらの混乱がないように。
=> [WIP]db_design_in_readme

Gemfile, Gemfile.lock, app/assets/stylesheets/_reset.scss, app/assets/stylesheets/_signup.scss, app/assets/stylesheets/application.scss, app/views/devise/shared/_footer.html.haml, app/views/devise/shared/_header.html.haml, app/views/entrances/signup.html.haml
サインアップ画面のフロント実装
ご意見をいただきたく早めに共有。
特に、ヘッダーとフッターは他のページと共通する部分なので、ご意見をいただきたい。
・現時点でのビューは https://gyazo.com/8141f3f29a694cbc604e1b4de9dc2db7 です。
コードを見ていただくにあたって　(haml/scssファイルに書いてあることと同じです。)
・各ボタン・ロゴなどのリンク先は全て今のページになっています。
・googleのロゴはfont awesomeのものを使用しており、カラーではありません。対応はできそうですが、簡単にできる方法があれば助言をお願いします。
・フッターのメルカリのロゴはヘッダーと同じものにしています。対応はできそうですが、簡単にできる方法があれば助言をお願いします。
=> [WIP] View of sign up

app/models/item.rb, app/models/user.rb, db/migrate/20200126082837_create_items.rb, test/fixtures/items.yml, test/models/item_test.rb
itemモデルの作成
マイグレーションファイルへの記述とuserモデルとのアソシエーションを組みました
itemモデルを取り急ぎ作って、個々の開発を進められるようにするため
=> itemモデルの作成

Gemfile, Gemfile.lock, app/assets/javascripts/application.js
gemfileにgemを加えて、requireしました。
適当なjsファイルを作ってコンソール出力テスト済みです。(そのファイルは削除してます)
=> JQueryを使えるように準備

app/models/user.rb
=> userモデルのバリデーション変更

Gemfile, app/assets/javascripts/application.js, app/assets/stylesheets/signup/_index.scss, app/views/users/index.html.haml
turbolinks関係のコードを削除
初期でjsの動作が実行されないのを防ぐため。
=> turbolinksの効果削除

Gemfile, Gemfile.lock, app/assets/javascripts/application.js
=> turbolinks復活

app/views/devise/sessions/new.html.haml
現状マスターがログインできない。
form_withのurl間違い修正しました。
動作確認、直りました↓
https://gyazo.com/db9b204bdc2d7053474c69f97ef8c36d
=> マスターがログインできない

app/views/branded_items/index.html.haml, app/views/categorized_items/index.html.haml, app/views/credit_cards/index.html.haml, app/views/credit_cards/new.html.haml, app/views/credit_cards/show.html.haml, app/views/guides/index.html.haml, app/views/myinfomations/_sidebar.html.haml, app/views/personal_informations/index.html.haml, config/breadcrumbs.rb
恐らく問題ないと思うので、特に意見がなければ、
明日にでもマージしたいと思います。
=> パンくずを現時点であるビューに実装

app/views/items/show.html.haml
=> 商品詳細ページ（ヘッダー編集）

app/controllers/products_controller.rb, spec/controllers/products_controller_spec.rb, spec/rails_helper.rb, spec/support/devise_macros.rb
- ログインしていないとProducts#newにアクセス出来ないようにした
- 単体テストでログインしている場合はhttps200が返りログインしていないと302が返ってくる(ログイン画面にredirectしているため)
- rspec spec/controllers/products_controller_spec.rb
=> 未ログインユーザーのproducts#newアクセス拒否

app/views/products/edit.html.haml, app/views/products/new.html.haml
商品出品と編集のフォームをItemモデルのenumから引き出すように編集
=> new画面enumから引き出すよう編集

app/controllers/items_controller.rb, app/controllers/products_controller.rb
ログインユーザーと出品者が一致する場合は、products/showに、
一致しない場合は、items/showにリダイレクトされるように修正
=> ログインユーザーに応じてitemsかproductsに行くように修正

app/controllers/items_controller.rb
・N+1問題一部解消しました。
解消前のターミナルの様子
https://gyazo.com/b44694a8bc3aa0aaad7d76f574015cd0
解消後のターミナルの様子
https://gyazo.com/accc5eace1b5c811659c3230c894255f
・N+1問題なのかわかりませんが、カテゴリーに関してはおそらく効率悪く取得しています。親カテゴリーから一発でその孫カテゴリー全てを配列で取得する方法がわかる方がいらっしゃいましたら、教えてください。
=> N+1問題解消と微量のリファクタリング

app/views/items/show.html.haml, app/views/products/new.html.haml, app/views/products/show.html.haml
showページに遷移した時にとりあえずエラー出ないようにする。
親・子・孫によってshow画面の条件分岐。
https://github.com/stefankroes/ancestry
=> 商品詳細ページ　選んだカテゴリーによって場合分け

app/controllers/items_controller.rb
大変申し訳ありません。
同名のリクエスト、リファクタリングのみで、N+1の改善が入ってなかったのでもう一度です。。。。
=> TOPページN+1問題(再)

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb
bundle exec rspec spec/controllers/items_controller_spec.rb
で確認できます。
spec/controllers/items_controller_spec.rb の変更のみ見てください。（他は別branchでマージしました。）
=> Topページのコントローラテスト

app/controllers/items_controller.rb
=> products#showへの遷移

spec/features/user_spec.rb, spec/spec_helper.rb, test/test_helper.rb
ログイン・ログアウトの動作確認。統合テストにて行う。
[テスト結果](https://gyazo.com/8f1f80f07e1177ab3d281789c01a0d9d)
予期せぬ不具合がないかテストする
https://qiita.com/annaPanda8170/items/6f07235b271063401482
❶rails db:reset
❷rails t (テストDBにデータを投入。seed.rbのデータが入るようにしてます）
❸bundle exec rspec spec/features/user_spec.rb
=> ユーザー　ログイン・ログアウトのテスト
